### ISSUE TITLE
Any plans for porting to RxJS 6?

### ISSUE THREAD

**Issue by vecernik** [KwintenP/rx-devtools#4]

**Comment by KwintenP** [comment]
There are no immediate plans. The entire idea of this library is built upon the idea of monkey pathing some methods. 

With the pipeable operators, this idea is kind of broken. Plus, it was still in alpha phase so it would basically mean a rewrite from scratch.

I might consider it if I have time but this instance, the answer is probably no.

**Comment by vecernik** [comment]
thanks, keep coding.

**Comment by orjandesmet** [comment]
I forked this and did a quick fix that works in RxJS 6 just to try something. 
Not gonna push to npmjs, though, because I'm not sure if it's correct and I haven't tested anything. It works basically the same, with the monkey patching. I only rewrote the operator to be a pipeable operator.

https://github.com/orjandesmet/rx-devtools/commit/3163aa8bd8e3cb4daa7ffa2cf4f1aa4b9a99d806#diff-25d902c24283ab8cfbac54dfa101ad31

**Comment by KwintenP** [comment]
Hi Orjan, 

Thanks for checking it out! Does this actually work inside the devtools?

**Comment by KwintenP** [comment]
I would actually suspect it doesn't work as, if I recall correctly, I'm overriding some functions that no longer exist due to the pipeable operators. 

Nevertheless, RxJS 7 is going to be a complete rewrite again internally, so the entire idea on how to get the know which events have happened at what instance need to be revisited again as well in the next version :(.

**Comment by orjandesmet** [comment]
> Hi Orjan,
> 
> Thanks for checking it out! Does this actually work inside the devtools?

Yes it does. I only did a quick test on a combined stream, but it appears to work the same as the original.

**Comment by KwintenP** [comment]
Hmm, ok. Didn't totally expect it. But I'm sure that some parts of the plugin will break. 

Any help to create a new version would be greatly appreciated! :)
